import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { Mail } from "lucide-react";
import { geistSans, geistMono, goodlyFont, inter, dmSans } from "../utils/font";
import "./globals.css";
import Header from "@/components/Header";
import { CartProvider } from "@/contexts/CartContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${goodlyFont.variable} ${inter.variable} ${dmSans.variable}  antialiased relative`}
      >
        <CartProvider>
          {/* header */}

          <Header />
          {children}

          {/* newsletter */}
          <section className="w-full flex flex-col font-inter items-center py-8 md:py-14 px-4 md:px-6">
            <h2 className="text-xl md:text-2xl lg:text-3xl font-bold text-gray-800 tracking-tighter text-center mb-2 md:mb-3">
              Subscribe to our newsletter
            </h2>
            <p className="text-sm md:text-base text-gray-500 max-w-[280px] md:max-w-[350px] lg:max-w-[400px] text-center mb-6 md:mb-8">
              Never miss a beat. Get a weekly dose of design inspiration,
              secrets, tips, trends, and banter in your inbox.
            </p>
            <form className="flex flex-col sm:flex-row gap-3 sm:gap-2 w-full max-w-sm sm:max-w-md lg:max-w-lg">
              <div className="flex items-center border border-gray-200 rounded-lg px-3 md:px-4 py-2 md:py-3 bg-white flex-1">
                <Mail className="w-4 h-4 md:w-5 md:h-5 text-gray-400 mr-2" />
                <input
                  type="email"
                  placeholder="Email address"
                  className="outline-none border-none bg-transparent flex-1 text-gray-700 text-sm md:text-base"
                />
              </div>
              <button
                type="submit"
                className="bg-primary text-white font-semibold rounded-lg px-4 md:px-6 py-2 md:py-3 text-sm md:text-base transition hover:bg-primary/90 whitespace-nowrap"
              >
                Subscribe
              </button>
            </form>
          </section>

          {/* footer */}
          <footer className="bg-gradient-to-t from-[#779BC1] via-[#9ABFDA] to-white pt-10 pb-8 px-10">
            <div className="max-w-7xl mx-auto w-full flex flex-col gap-6">
              {/* Top Row */}
              <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-6">
                {/* Logo */}
                <div>
                  <Link href="/">
                    <Image
                      src="/imgs/brand-logo.png"
                      alt="Logo"
                      width={40}
                      height={40}
                      className="inline-block align-middle"
                    />
                  </Link>
                </div>
                {/* Contact & Social */}
                <div className="flex flex-col text-white md:flex-row md:items-center gap-4 md:gap-8">
                  <div className="text-sm  font-dm-sans">
                    Contact us:{" "}
                    <a
                      href="mailto:hello@klat32.com"
                      className="font-semibold hover:underline text-primary"
                    >
                      hello@klat32.com
                    </a>
                  </div>
                  <div className="flex items-center gap-3">
                    <span className="text-sm  font-dm-sans">Follow Us</span>
                    <a
                      href="#"
                      aria-label="Facebook"
                      className="size-10 rounded-full bg-white/20 flex items-center justify-center"
                    >
                      <div className=" relative size-5">
                        <Image fill src="/icon/facebook.svg" alt="facebook" />
                      </div>
                    </a>
                    <a
                      href="#"
                      aria-label="Twitter"
                      className="size-10 rounded-full bg-white/20 flex items-center justify-center"
                    >
                      <span className=" relative size-5">
                        <Image fill src="/icon/twitter.svg" alt="twitter" />
                      </span>
                    </a>
                    <a
                      href="#"
                      aria-label="Instagram"
                      className="size-10 rounded-full bg-white/20 flex items-center justify-center"
                    >
                      <span className=" relative size-5">
                        <Image fill src="/icon/instagram.svg" alt="instagram" />
                      </span>
                    </a>
                    <a
                      href="#"
                      aria-label="LinkedIn"
                      className="size-10 rounded-full bg-white/20 flex items-center justify-center"
                    >
                      <span className=" relative size-5">
                        <Image fill src="/icon/linkedin.svg" alt="linkedin" />
                      </span>
                    </a>
                  </div>
                </div>
              </div>
              {/* Bottom Row */}
              <div className="flex flex-col md:flex-row md:justify-between items-start md:items-center mt-2">
                <div className="flex gap-8 text-white text-sm font-dm-sans">
                  <Link href="/privacy-policy" className="hover:underline">
                    Privacy Policy
                  </Link>
                  <Link href="/terms" className="hover:underline">
                    Terms of Use
                  </Link>
                </div>
                {/* Copyright */}
                <div className="text-xs text-white font-dm-sans text-right">
                  © 2023. Powered by Klat-32. All Rights Reserved.
                </div>
              </div>
            </div>
          </footer>
        </CartProvider>
      </body>
    </html>
  );
}
