import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { Mail } from "lucide-react";
import { geistSans, geistMono, goodlyFont, inter, dmSans } from "../utils/font";
import "./globals.css";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${goodlyFont.variable} ${inter.variable} ${dmSans.variable}  antialiased relative`}
      >
        {/* header */}
        <header className="absolute top-0 left-0 w-full z-10">
          <nav className=" flex items-center py-4 justify-between px-[clamp(1rem,5vw,112px)]">
            <Link href={"/"}>
              <Image
                src="/imgs/brand-logo.png"
                alt="Logo"
                width={50}
                height={50}
                className="inline-block align-middle"
              />
            </Link>
            <ul className="flex gap-8 py-4 px-10  font-dm-sans text-white bg-[#F7F9FC33] rounded-[2.5rem]">
              <li>
                <Link className=" font-semibold" href={"/"}>
                  Home
                </Link>
              </li>
              <li>
                <Link className=" font-semibold" href={"#"}>
                  Features
                </Link>
              </li>
              <li>
                <Link className=" font-semibold" href={"/faqs"}>
                  FAQs
                </Link>
              </li>
              <li>
                <Link className=" font-semibold" href={"/terms"}>
                  Terms of Condition
                </Link>
              </li>
            </ul>
            <button className=" bg-primary text-white font-semibold rounded-[2.5rem] font-inter py-4 px-6 flex items-center justify-center">
              Join waitlist
            </button>
          </nav>
        </header>
        {children}
        {/* newsletter */}
        <section className="w-full flex flex-col items-center py-14">
          <h2 className="text-2xl font-bold  text-center mb-2">
            Subscribe to our newsletter
          </h2>
          <p className="text-gray-500 text-center mb-6 max-w-md">
            Never miss a beat.
            <br />
            Get a weekly dose of design inspiration, secrets, tips, trends, and
            banter in your inbox.
          </p>
          <form className="flex gap-2 w-full max-w-md">
            <div className="flex items-center border border-gray-200 rounded-lg px-4 py-2 bg-white flex-1">
              <Mail className="w-5 h-5 text-gray-400 mr-2" />
              <input
                type="email"
                placeholder="Email address"
                className="outline-none border-none bg-transparent flex-1 text-gray-700 text-sm"
              />
            </div>
            <button
              type="submit"
              className="bg-[#F25C05] hover:bg-[#d94e00] text-white font-semibold rounded-lg px-6 py-2 text-sm transition"
            >
              Subscribe
            </button>
          </form>
        </section>
        {/* footer */}
        <footer className="bg-gradient-to-t from-[#779BC1] via-[#9ABFDA] to-white pt-10 pb-8 px-10">
          <div className="max-w-7xl mx-auto w-full flex flex-col gap-6">
            {/* Top Row */}
            <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-6">
              {/* Logo */}
              <div>
                <Link href="/">
                  <Image
                    src="/imgs/brand-logo.png"
                    alt="Logo"
                    width={40}
                    height={40}
                    className="inline-block align-middle"
                  />
                </Link>
              </div>
              {/* Contact & Social */}
              <div className="flex flex-col text-white md:flex-row md:items-center gap-4 md:gap-8">
                <div className="text-sm  font-dm-sans">
                  Contact us:{" "}
                  <a
                    href="mailto:hello@klat32.com"
                    className="font-semibold hover:underline text-primary"
                  >
                    hello@klat32.com
                  </a>
                </div>
                <div className="flex items-center gap-3">
                  <span className="text-sm  font-dm-sans">Follow Us</span>
                  <a
                    href="#"
                    aria-label="Facebook"
                    className="size-10 rounded-full bg-white/20 flex items-center justify-center"
                  >
                    <div className=" relative size-5">
                      <Image fill src="/icon/facebook.svg" alt="facebook" />
                    </div>
                  </a>
                  <a
                    href="#"
                    aria-label="Twitter"
                    className="size-10 rounded-full bg-white/20 flex items-center justify-center"
                  >
                    <span className=" relative size-5">
                      <Image fill src="/icon/twitter.svg" alt="twitter" />
                    </span>
                  </a>
                  <a
                    href="#"
                    aria-label="Instagram"
                    className="size-10 rounded-full bg-white/20 flex items-center justify-center"
                  >
                    <span className=" relative size-5">
                      <Image fill src="/icon/instagram.svg" alt="instagram" />
                    </span>
                  </a>
                  <a
                    href="#"
                    aria-label="LinkedIn"
                    className="size-10 rounded-full bg-white/20 flex items-center justify-center"
                  >
                    <span className=" relative size-5">
                      <Image fill src="/icon/linkedin.svg" alt="linkedin" />
                    </span>
                  </a>
                </div>
              </div>
            </div>
            {/* Bottom Row */}
            <div className="flex flex-col md:flex-row md:justify-between items-start md:items-center mt-2">
              <div className="flex gap-8 text-white text-sm font-dm-sans">
                <Link href="/privacy-policy" className="hover:underline">
                  Privacy Policy
                </Link>
                <Link href="/terms" className="hover:underline">
                  Terms of Use
                </Link>
              </div>
              {/* Copyright */}
              <div className="text-xs text-white font-dm-sans text-right">
                © 2023. Powered by Klat-32. All Rights Reserved.
              </div>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
